package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private double amount;
     private Double moneyShare;

    public Account() {
    }

	
    public Account(Users users, double amount) {
        this.users = users;
        this.amount = amount;
    }
    public Account(Users users, double amount, Double moneyShare) {
       this.users = users;
       this.amount = amount;
       this.moneyShare = moneyShare;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Double getMoneyShare() {
        return this.moneyShare;
    }
    
    public void setMoneyShare(Double moneyShare) {
        this.moneyShare = moneyShare;
    }




}


