package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShoppingCart generated by hbm2java
 */
public class ShoppingCart  implements java.io.Serializable {


     private ShoppingCartId id;
     private Users users;
     private double total;
     private Date shoppingCartDate;
     private Set ordersHasProductses = new HashSet(0);

    public ShoppingCart() {
    }

	
    public ShoppingCart(ShoppingCartId id, Users users, double total) {
        this.id = id;
        this.users = users;
        this.total = total;
    }
    public ShoppingCart(ShoppingCartId id, Users users, double total, Date shoppingCartDate, Set ordersHasProductses) {
       this.id = id;
       this.users = users;
       this.total = total;
       this.shoppingCartDate = shoppingCartDate;
       this.ordersHasProductses = ordersHasProductses;
    }
   
    public ShoppingCartId getId() {
        return this.id;
    }
    
    public void setId(ShoppingCartId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Date getShoppingCartDate() {
        return this.shoppingCartDate;
    }
    
    public void setShoppingCartDate(Date shoppingCartDate) {
        this.shoppingCartDate = shoppingCartDate;
    }
    public Set getOrdersHasProductses() {
        return this.ordersHasProductses;
    }
    
    public void setOrdersHasProductses(Set ordersHasProductses) {
        this.ordersHasProductses = ordersHasProductses;
    }




}


