package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0



/**
 * ShoppingCartId generated by hbm2java
 */
public class ShoppingCartId  implements java.io.Serializable {


     private int id;
     private int usersId;

    public ShoppingCartId() {
    }

    public ShoppingCartId(int id, int usersId) {
       this.id = id;
       this.usersId = usersId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ShoppingCartId) ) return false;
		 ShoppingCartId castOther = ( ShoppingCartId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUsersId()==castOther.getUsersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUsersId();
         return result;
   }   


}


