package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0



/**
 * TransactionsId generated by hbm2java
 */
public class TransactionsId  implements java.io.Serializable {


     private int transactionId;
     private int fromId;
     private int toId;

    public TransactionsId() {
    }

    public TransactionsId(int transactionId, int fromId, int toId) {
       this.transactionId = transactionId;
       this.fromId = fromId;
       this.toId = toId;
    }
   
    public int getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }
    public int getFromId() {
        return this.fromId;
    }
    
    public void setFromId(int fromId) {
        this.fromId = fromId;
    }
    public int getToId() {
        return this.toId;
    }
    
    public void setToId(int toId) {
        this.toId = toId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransactionsId) ) return false;
		 TransactionsId castOther = ( TransactionsId ) other; 
         
		 return (this.getTransactionId()==castOther.getTransactionId())
 && (this.getFromId()==castOther.getFromId())
 && (this.getToId()==castOther.getToId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTransactionId();
         result = 37 * result + this.getFromId();
         result = 37 * result + this.getToId();
         return result;
   }   

    @Override
    public String toString()
    {
        return String.valueOf(transactionId);
    }

}


