package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private String address;
     private String role;
     private Set orderses = new HashSet(0);
     private Set shoppingCarts = new HashSet(0);
     private Set transactionsesForToId = new HashSet(0);
     private Set transactionsesForFromId = new HashSet(0);
     private Set wishlists = new HashSet(0);
     private Set accounts = new HashSet(0);
     private Set productses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String password, String email, String address, String role) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.address = address;
        this.role = role;
    }
    public Users(String username, String password, String email, String address, String role, Set orderses, Set shoppingCarts, Set transactionsesForToId, Set transactionsesForFromId, Set wishlists, Set accounts, Set productses) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.address = address;
       this.role = role;
       this.orderses = orderses;
       this.shoppingCarts = shoppingCarts;
       this.transactionsesForToId = transactionsesForToId;
       this.transactionsesForFromId = transactionsesForFromId;
       this.wishlists = wishlists;
       this.accounts = accounts;
       this.productses = productses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getShoppingCarts() {
        return this.shoppingCarts;
    }
    
    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }
    public Set getTransactionsesForToId() {
        return this.transactionsesForToId;
    }
    
    public void setTransactionsesForToId(Set transactionsesForToId) {
        this.transactionsesForToId = transactionsesForToId;
    }
    public Set getTransactionsesForFromId() {
        return this.transactionsesForFromId;
    }
    
    public void setTransactionsesForFromId(Set transactionsesForFromId) {
        this.transactionsesForFromId = transactionsesForFromId;
    }
    public Set getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set wishlists) {
        this.wishlists = wishlists;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }

    @Override
    public String toString()
    {
        return String.valueOf(id);
    }
    
}


