package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private WishlistId id;
     private Users users;
     private Products products;

    public Wishlist() {
    }

    public Wishlist(WishlistId id, Users users, Products products) {
       this.id = id;
       this.users = users;
       this.products = products;
    }
   
    public WishlistId getId() {
        return this.id;
    }
    
    public void setId(WishlistId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }




}


