package database;
// Generated Feb 5, 2018 1:12:41 PM by Hibernate Tools 3.6.0



/**
 * WishlistId generated by hbm2java
 */
public class WishlistId  implements java.io.Serializable {


     private int id;
     private int usersId;
     private int productsId;

    public WishlistId() {
    }

    public WishlistId(int id, int usersId, int productsId) {
       this.id = id;
       this.usersId = usersId;
       this.productsId = productsId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }
    public int getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(int productsId) {
        this.productsId = productsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WishlistId) ) return false;
		 WishlistId castOther = ( WishlistId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUsersId()==castOther.getUsersId())
 && (this.getProductsId()==castOther.getProductsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUsersId();
         result = 37 * result + this.getProductsId();
         return result;
   }   


}


